# 출력층 설계 (Output layer)

In [1]:
!pip3 install torch torchvision torchaudio

### 소프트맥스 오버플로우 방지`

In [2]:
import numpy as np

def softmax(x):
    exp_x = np.exp(x)
    return exp_x/ np.sum(exp_x)

def stable_softmax(x):
    exp_x = np.exp(x-np.max(x))
    return exp_x/ np.sum(exp_x)
    
    
x = np.array([1000,1001,1002])

print(softmax(x))
print(stable_softmax(x))

[nan nan nan]
[0.09003057 0.24472847 0.66524096]


C:\Users\ljh10\AppData\Local\Temp\ipykernel_31556\3084428099.py:4: RuntimeWarning: overflow encountered in exp
  exp_x = np.exp(x)
C:\Users\ljh10\AppData\Local\Temp\ipykernel_31556\3084428099.py:5: RuntimeWarning: invalid value encountered in divide
  return exp_x/ np.sum(exp_x)


- pytorch 라이브러리 함수 사용

In [8]:
import torch
import torch.nn.functional as F

x = torch.tensor([1000,1001,1002], dtype=torch.float32)
print(x.dtype)

softmax_output = F.softmax(x, dim=0) # dim: softmax를 적용할 축
print(softmax_output)

sigmoid_output = torch.sigmoid(x)
print(sigmoid_output)

torch.float32
tensor([0.0900, 0.2447, 0.6652])
tensor([1., 1., 1.])


# 손실 함수와 연계

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim

# 간단한 다중 클래스 분류 모델 정의 (입력 값: 5개, 출력: 3 클래스)
class SimpleMultiClassModel(nn.Module):
    def __init__(self):
        super(SimpleMultiClassModel, self).__init__()
        self.fc = nn.Linear(5,3)
        
    def forward(self,x):
        return self.fc(x)
    
model = SimpleMultiClassModel()
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.01)

# 데이터 생성
inputs = torch.randn(4,5)
labels = torch.tensor([0,2,1,0])

for _ in range(10):
    preds = model(inputs) #순전파
    loss = criterion(preds, labels)   #손실 계산
    print(loss.item())

    optimizer.zero_grad()   # 이전 단계에서 계산된 기울기를 0으로 초기화
    loss.backward()         # 손실에 대한 역전파 수행
    optimizer.step()        # 계산된 기울기를 사용하여 옵티마이저가 모델의 파라미터 업데이트


1.1399801969528198
1.1046864986419678
1.0703015327453613
1.0368659496307373
1.0044174194335938
0.9729882478713989
0.9426063299179077
0.913293182849884
0.885063886642456
0.857926607131958


f